### ISSUE TITLE
Update overlaps when a checkbox is clicked

### ISSUE THREAD

**Issue by hftf** [hftf/coords#31]

**Comment by MattiasBuelens** [comment]
It comes down to adding this snippet in the right place:

``` javascript
if(this.state.coords.length) {
    list_overlaps(this.state.coords);
}
```

Problem is _where_ exactly this should go. You can do it in `setState`, but then you're doing too much work when a whole menu is rotated (`rotateStates`) or when loading state from the URL (`setAll`). Ideally, you want to call it at most once per trigger...

**Comment by hftf** [comment]
How about a new method that takes care of everything (`list_overlaps` and `replaceState`) at the end of a “transaction”?

**Comment by MattiasBuelens** [comment]
Sounds reasonable. Make `State` use private functions to do individual operations (changing the state of one or more inputs, updating the URL,...) and expose public functions which use these individual operations and _afterwards_ call the private "transaction finalizer".

We'll need a bit of refactoring to make sure the callers can do everything in one transaction. For example, `reset_all` in `coords.js` currently calls `State` functions multiple times, ideally we want to reduce that to just one transaction call.

**Comment by hftf** [comment]
:+1:
