### ISSUE TITLE
X/Y screens

### ISSUE THREAD

**Issue by hftf** [hftf/coords#56]
[Some screenshots](http://www.reddit.com/r/twitchplayspokemon/comments/2avc2q/here_are_pokemon_xy_touchscreen_screenshots/)

**Comment by MattiasBuelens** [comment]
Any idea how we are going to actually get coordinates for 3DS games? Sure, dekuNukem is awesome for making and uploading high-quality screenshots, but we don't know the hit boxes on these things. :stuck_out_tongue:

**Comment by MattiasBuelens** [comment]
[dekuNukem on reddit](http://www.reddit.com/r/twitchplayspokemon/comments/2avc2q/here_are_pokemon_xy_touchscreen_screenshots/cizaf46):

> Unfortunately I don't have hitbox data of those buttons.
> 
> And the touchscreen accuracy will not likely to be pixel prefect because we're spoofing the hardware.
> 
> It's still fairly accurate though, around ±3 pixel for a given coordinate, so I would suggest against pressing at the very edge of a button.

The accuracy thing is definitely something to take into account, pixel perfection is no longer possible. Other than that, it looks like we're going to need trial and error to "optimize" the hit boxes.

**Comment by hftf** [comment]
The only option I can think of is to just ask the dev to open the stream for coordinates testing, etc.

**Comment by MattiasBuelens** [comment]
I doubt he'd do that, given that X will probably be starting fairly soon (1-2 weeks)...

**Comment by hftf** [comment]
I don't see why that would be a reason not to :confused:

**Comment by MattiasBuelens** [comment]
He can't open the stream now, that'd just mean we start playing X before we finish Black 2. :stuck_out_tongue: He'd have to do a private stream for only a few players with the sole purpose of testing coordinates... I doubt he'd want to do that.

**Comment by hftf** [comment]
He already tested it/streamed it several times in the past. I also don't see why it would need to be private. Anyway this is getting off-topic.
